#include "Reflection.h"

namespace tyr
{
	TYR_REFL_CLASS_START(int, 0);
	TYR_REFL_CLASS_END();

	TYR_REFL_CLASS_START(uint8, 0);
	TYR_REFL_CLASS_END();

	TYR_REFL_CLASS_START(uint16, 0);
	TYR_REFL_CLASS_END();

	TYR_REFL_CLASS_START(uint, 0);
	TYR_REFL_CLASS_END();

	TYR_REFL_CLASS_START(uint64, 0);
	TYR_REFL_CLASS_END();

	TYR_REFL_CLASS_START(size_t, 0);
	TYR_REFL_CLASS_END();

	TYR_REFL_CLASS_START(float, 0);
	TYR_REFL_CLASS_END();
}